[llms-txt]
output_dir = "data"

# PyPI packages
pypi = [
    "alembic",
    "ansible",
    "async-lru",
    "backoff",
    "beautifulsoup4",
    "boto3",
    "cachetools",
    "celery",
    "click",
    "coverage",
    "django",
    "docker",
    "fabric",
    "fastapi",
    "flask",
    "gunicorn",
    "hypothesis",
    "ipython",
    "jiter",
    "jupyter",
    "keras",
    "kubernetes",
    "lxml",
    "matplotlib",
    "mock",
    "mypy",
    "notebook",
    "nose",
    "numpy",
    "opencv-python",
    "openai",
    "opentelemetry-api",
    "orjson",
    "pandas",
    "paramiko",
    "pillow",
    "plotly",
    "pydantic",
    "pybase64",
    "pyjwt",
    "pylint",
    "pytest",
    "pytest-cov",
    "pyyaml",
    "redis",
    "requests",
    "scikit-learn",
    "scipy",
    "scrapy",
    "seaborn",
    "sphinx",
    "sqlalchemy",
    "starlette",
    "tenacity",
    "tensorflow",
    "tox",
    "transformers",
    "uvicorn",
    "virtualenv"
]

# NPM packages
npm = []

# Cargo (Rust) packages
cargo = []

# Direct documentation URLs
urls = ["https://docs.anthropic.com/llms-full.txt"]

[project.scripts]
docs = "llms_txt.main:main"
